name: 'ðŸ“¦ Test codebase'

on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      HAS_UNIT_TEST:
        required: true
        type: boolean
      NPM_REGISTRY:
        description: "Hostname of NPM registry to setup"
        required: false
        type: string
        default: registry.npmjs.org
      NPM_SCOPE:
        description: "Account owner to use as GitHub Packages scope"
        type: string
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_RO }}
    steps:
      - name: Check if codebase tests are difined within package.json
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/npm/check-tests@feature/{LM-10511}-npm-publishing
        id: check-tests
      - name: Setup node
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/npm/setup-node@feature/{LM-10511}-npm-publishing
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
      - name: Download and unzip dependencies artficat
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/git/download-artifact@feature/{LM-10511}-npm-publishing
      - name: Run unit tests
        if: inputs.HAS_UNIT_TEST
        run: npm test
      # - name: Run unit tests
      #   if: ${{ steps.check-tests.outputs.HAS_UNIT_TEST == 'true' }}
      #   run: npm run test