name: Build & Test

on:
  workflow_call:
    inputs:
      HAS_UNIT_TEST:
        required: false
        type: boolean
        default: false
      GH_BASE_REF:
        required: false
        type: string
      GH_HEAD_REF:
        required: false
        type: string
      VALIDATE_GITFLOW:
        required: false
        type: boolean
        default: false
      NODE_VERSION:
        required: true
        type: string
      USE_PROTOC:
        required: false
        type: boolean
        default: false

jobs:
  gitflow-validation:
    if: ${{ inputs.VALIDATE_GITFLOW || ( inputs.GH_BASE_REF != '' && inputs.GH_HEAD_REF != '' ) }}
    uses: Lattice-Trade/membrane-github-template-actions/.github/workflows/gh-validate-gitflow.v1.yml@main

  install:
    needs: gitflow-validation
    if: |
      always() &&
      (needs.gitflow-validation.result == 'success' || needs.gitflow-validation.result == 'skipped')
    uses: Lattice-Trade/membrane-github-template-actions/.github/workflows/typescript-install.v1.yml@main
    with:
      NODE_VERSION: ${{ inputs.NODE_VERSION }}
    secrets: inherit

  lint:
    needs: install
    if: always() && needs.install.result == 'success'
    uses: Lattice-Trade/membrane-github-template-actions/.github/workflows/typescript-lint.v1.yml@main
    with:
      NODE_VERSION: ${{ inputs.NODE_VERSION }}
    secrets: inherit

  test:
    needs: install
    if: always() && needs.install.result == 'success'
    uses: Lattice-Trade/membrane-github-template-actions/.github/workflows/typescript-test.v1.yml@main
    with:
      NODE_VERSION: ${{ inputs.NODE_VERSION }}
      HAS_UNIT_TEST: ${{ inputs.HAS_UNIT_TEST }}
    secrets: inherit

  build:
    needs: [test, lint]
    if: |
      always() &&
      needs.lint.result == 'success' &&
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    uses: Lattice-Trade/membrane-github-template-actions/.github/workflows/typescript-build.v1.yml@feature/INF-198-proto-sdk
    with:
      NODE_VERSION: ${{ inputs.NODE_VERSION }}
      USE_PROTOC: ${{ inputs.USE_PROTOC }}
    secrets: inherit