name: 'ðŸ“¦ Test codebase'

on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      HAS_UNIT_TEST:
        required: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Check if codebase tests are difined within package.json
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/npm/check-tests.v1@main
        id: check-tests
      - name: Setup node
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/npm/setup-node.v1@main
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
      - name: Download artifact of dependencies
        uses: actions/download-artifact@v3
        with:
          name: node_modules.tgz
          path: .
      - name: Unzip artifact of dependencies
        run: tar -xzf node_modules.tgz
        shell: bash
      - name: Run unit tests
        if: inputs.HAS_UNIT_TEST
        run: npm test
      # - name: Run unit tests
      #   if: ${{ steps.check-tests.outputs.HAS_UNIT_TEST == 'true' }}
      #   run: npm run test